### ISSUE TITLE
ci/cd for vckit ui

### ISSUE THREAD

**Issue by arpentnoir** [uncefact/project-vckit#11]
### Description

The goal of this task is to set up continuous integration and deployment for the VCKit SPA to be deployed to S3/CloudFront using GitHub Actions. The SPA should be accessible at test.uncefact.org/vckit/demo. Note that the UN/CEFACT Supply Chain Traceability Project already exists, and this task should take that into account. Additionally, the SPA will need to be modified to be served at a subfolder of the domain.

### Requirements

- VCKit SPA should have a stable and reliable deployment pipeline that is easy to use for developers.
- The deployment pipeline should ensure that the latest version of the SPA is automatically built, tested and deployed to S3/CloudFront every time there is a change to the codebase.
- The deployed SPA should be accessible at the URL test.uncefact.org/vckit/demo.
- The SPA should be modified to be served at a subfolder of the domain to avoid conflicts with other projects.

### Subtasks

- [ ] Configure GitHub Actions to build, test, and deploy the VCKit SPA to S3/CloudFront.
- [ ] Modify the SPA to be served at a subfolder of the domain to avoid conflicts.
- [ ] Set up the S3 bucket and CloudFront distribution to host the SPA.
- [ ] Configure the GitHub Actions workflow to automatically trigger when there is a change to the codebase.
- [ ] Test the deployment pipeline to ensure that the latest version of the SPA is being deployed to S3/CloudFront and is accessible at test.uncefact.org/vckit/demo.

Once all subtasks are completed, the VCKit SPA will have a CI/CD pipeline set up for continuous deployment to S3/CloudFront using GitHub Actions. The SPA will be accessible at test.uncefact.org/vckit/demo and will have been modified to be served at a subfolder of the domain.
