### ISSUE TITLE
issuer profile

### ISSUE THREAD

**Issue by arpentnoir** [uncefact/project-vckit#25]
## Create and Manage Issuer Profile
API endpoint to create and manage issuer profiles with proper authorization. Issuer profiles allow users to allocate keys for issuing credentials and communicating over DIDComm.

### User Story
As a developer integrating with vckit, I want to be able to create and manage issuer profiles via API, so that I can programmatically allocate keys for issuing credentials and communicating over DIDComm.

### Acceptance Criteria
- [ ] API endpoint is available at `/api/issuerprofile`
- [ ] Endpoint allows for creation and management of issuer profiles
- [ ] Endpoint returns an appropriate response status code and message upon successful creation or management of an issuer profile
- [ ] Endpoint conforms to the appropriate W3C VC HTTP API specification
- [ ] Endpoint passes the relevant traceability interop tests
- [ ] Endpoint is secured with proper authorization mechanisms

### Task List
- [ ] Build a feature list for the create and manage issuer profile feature
- [ ] Plan the design, construction, and testing activities for the feature
- [ ] Design the feature by creating a high-level design of the classes, interfaces, and data structures that are required to implement it
- [ ] Build the feature by writing code, creating tests, and integrating the feature with the rest of the system
- [ ] Test the feature by running automated tests and performing manual testing to ensure that it meets the acceptance criteria and works correctly

### Sub-Features
None

### Additional Information
Issuer profiles allow users to manage their credentials and keypairs for issuing credentials and communicating over DIDComm. More information on DIDComm can be found at https://identity.foundation/didcomm-messaging/spec/.
