### ISSUE TITLE
traceability interop postman collection

### ISSUE THREAD

**Issue by arpentnoir** [uncefact/project-vckit#29]
## Traceability Interop Postman Collection

A Postman collection to facilitate the testing and verification of traceability interop within the vckit ecosystem.

### Description
The purpose of this feature is to provide a Postman collection that developers can use to test and verify the traceability interop functionality of vckit. This collection will contain a set of requests and tests that will ensure that traceability data is being exchanged correctly between different entities within the ecosystem.

### Acceptance Criteria
- [ ] Postman collection is available for download or import
- [ ] Collection contains a set of requests and tests that verify traceability interop
- [ ] Collection conforms to the appropriate W3C VC HTTP API specification
- [ ] Collection passes the relevant traceability interop tests

### Task List
- [ ] Design the feature by creating a high-level plan for the requests and tests that need to be included in the collection
- [ ] Build the feature by creating the Postman collection and adding the necessary requests and tests
- [ ] Test the feature by running the collection and verifying that it meets the acceptance criteria

### Sub-Features
None

### Additional Information
Traceability interop is a critical feature of vckit, as it ensures that data is being exchanged securely and accurately between different entities within the ecosystem. By providing a Postman collection that developers can use to test and verify this functionality, we can ensure that vckit is being used effectively and efficiently.
