### ISSUE TITLE
"deploy to" button

### ISSUE THREAD

**Issue by arpentnoir** [uncefact/project-vckit#9]
### Description

The goal of this task is to add a "Deploy to" button to the VCKit project's root readme file that allows developers to quickly and easily deploy the project to DigitalOcean. DigitalOcean is chosen as the first option based on its ease of use, developer experience, and popularity. In future work, we will enable simplified deployments to other cloud providers.

### Requirements

- The "Deploy to" button should be added to the VCKit project's root readme file.
- DigitalOcean should be chosen as the first option for deploying the project.
- Future work should include enabling simplified deployments to other cloud providers.

### Subtasks

- [ ] Configure the VCKit project for deployment to DigitalOcean, including setting up the necessary infrastructure and dependencies.
- [ ] Create a "Deploy to DigitalOcean" button and add it to the VCKit project's root readme file.
- [ ] Test the "Deploy to DigitalOcean" button to ensure it deploys the project correctly.
- [ ] Document the process for deploying the project to DigitalOcean in the project's documentation.

In future work, we will enable simplified deployments to other cloud providers. This will involve creating additional "Deploy to" buttons and configuring the necessary infrastructure and dependencies for each cloud provider. 

Once all the subtasks are completed, we should have a "Deploy to DigitalOcean" button on the VCKit project's root readme file that allows developers to quickly and easily deploy the project to DigitalOcean, with future work planned to enable simplified deployments to other cloud providers. The project's documentation should also be updated to include instructions for deploying to DigitalOcean.
